services:
  - type: web
    name: african-gdp-api
    env: python
    region: frankfurt
    buildCommand: pip install -r summative/API/requirements.txt
    startCommand: cd summative/API && uvicorn prediction:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
